services:
  qa:
    build:
      context: ../..                      # repo root
      dockerfile: deployments/docker/Dockerfile
    env_file:
      - env/.env                          # set CRON_EXPR, TZ here
    working_dir: /app
    tty: true
    restart: unless-stopped